import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { createHash } from 'crypto'
import { readFileSync, writeFileSync, unlinkSync, existsSync, mkdirSync } from 'fs'
import { resolve } from 'path'

// Non-obvious entry point name — attackers probe "index.html" by default
const ENTRY = 'portal.html'

// ── SRI + rename plugin ────────────────────────────────────────────────
// Runs after every build:
//  1. Computes SHA-384 of every JS/CSS bundle
//  2. Injects integrity + crossorigin attributes into HTML
//  3. Renames index.html → ENTRY, removes the predictable filename
//  4. Writes a fresh .htaccess with the correct entry name baked in
function securePlugin() {
  return {
    name: 'vite-secure-sri',
    enforce: 'post',
    closeBundle() {
      const dist = resolve('dist')
      const idx  = resolve(dist, 'index.html')
      if (!existsSync(idx)) return

      let html = readFileSync(idx, 'utf-8')

      // Compute SHA-384 of a dist asset
      const sri = (href) => {
        const p = resolve(dist, href.replace(/^\//, ''))
        if (!existsSync(p)) return null
        return `sha384-${createHash('sha384').update(readFileSync(p)).digest('base64')}`
      }

      // Only add crossorigin if not already present
      const xo = (tag) => tag.includes('crossorigin') ? '' : ' crossorigin="anonymous"'

      // Inject integrity into any <link rel="stylesheet" href="/assets/...css">
      html = html.replace(/<link\b[^>]*href="(\/assets\/[^"]+\.css)"[^>]*\/?>/g, tag => {
        if (tag.includes('integrity=')) return tag
        const m = tag.match(/href="(\/assets\/[^"]+\.css)"/)
        if (!m) return tag
        const hash = sri(m[1])
        if (!hash) return tag
        return tag.replace(/(\/?>)$/, ` integrity="${hash}"${xo(tag)}$1`)
      })

      // Inject integrity into any <script src="/assets/...js"> (module or classic)
      html = html.replace(/<script\b[^>]*src="(\/assets\/[^"]+\.js)"[^>]*>/g, tag => {
        if (tag.includes('integrity=')) return tag
        const m = tag.match(/src="(\/assets\/[^"]+\.js)"/)
        if (!m) return tag
        const hash = sri(m[1])
        if (!hash) return tag
        return tag.replace(/>$/, ` integrity="${hash}"${xo(tag)}>`)
      })

      // Convert <script type="module" ...> → <script defer ...>
      // IIFE bundles don't use ES module semantics, so type="module" is wrong.
      // More importantly: classic <script defer> has NO strict MIME type enforcement.
      // The browser will execute it even if the server returns a wrong Content-Type.
      html = html.replace(
        /<script\b[^>]*\bsrc="(\/assets\/[^"]+\.js)"[^>]*><\/script>/g,
        (tag) => {
          const src       = (tag.match(/src="([^"]+)"/)       || [])[1] || ''
          const integrity = (tag.match(/integrity="([^"]+)"/) || [])[1]
          const iAttr     = integrity ? ` integrity="${integrity}"` : ''
          return `<script defer src="${src}"${iAttr}></script>`
        }
      )

      // Write SRI-enhanced HTML under the non-obvious entry name
      const dest = resolve(dist, ENTRY)
      writeFileSync(dest, html)
      try { if (idx !== dest) unlinkSync(idx) } catch {}

      // Write fresh .htaccess files — overwrites any rogue versions left by attackers
      writeFileSync(resolve(dist, '.htaccess'), htaccess(ENTRY))

      const assetsDir = resolve(dist, 'assets')
      mkdirSync(assetsDir, { recursive: true })
      writeFileSync(resolve(assetsDir, '.htaccess'), assetsHtaccess())

      console.log(`\n  ✓ SRI hashes injected`)
      console.log(`  ✓ Entry file: ${ENTRY} (index.html removed)`)
      console.log(`  ✓ .htaccess + assets/.htaccess regenerated\n`)
    },
  }
}

// ── assets/.htaccess generator ────────────────────────────────────────
// Placed inside dist/assets/ on every build.
// Purpose: override any rogue .htaccess an attacker may have left there,
// and force correct MIME types so JS/CSS always loads properly.
function assetsHtaccess() {
  return `# ================================================================
#  Home Security Insights — Assets directory hardening
#  Auto-generated by build — do not edit manually
# ================================================================

Options -Indexes -ExecCGI -Includes

# Force correct MIME types regardless of server defaults.
# This overrides any malicious .htaccess previously planted here.
AddType application/javascript .js
AddType text/css               .css
AddType image/svg+xml          .svg
AddType image/png              .png
AddType image/jpeg             .jpg .jpeg
AddType image/webp             .webp
AddType font/woff2             .woff2
AddType font/woff              .woff

# Block execution of any server-side scripts uploaded by attackers
<FilesMatch "\\.(php|php3|php4|php5|php7|php8|phtml|phar|pl|cgi|py|rb|asp|aspx|jsp|sh|bash|exe|dll)$">
  Require all denied
</FilesMatch>

# Only static asset types are allowed in this directory
<FilesMatch "^(?!.*\\.(js|css|svg|png|jpg|jpeg|webp|gif|ico|woff2|woff|ttf)$).*$">
  Require all denied
</FilesMatch>

# Immutable cache for hashed bundles
<IfModule mod_headers.c>
  <FilesMatch "\\.(js|css)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>
`
}

// ── root .htaccess generator ───────────────────────────────────────────
function htaccess(entry) {
  return `# ================================================================
#  Home Security Insights — Hardened Apache Config
#  Auto-generated by build — do not edit manually
# ================================================================

Options -Indexes -ExecCGI -Includes
ServerSignature Off

# ── Explicit MIME types ───────────────────────────────────
# Forces Apache to serve these types correctly regardless of
# the server's global mime.types configuration.
AddType application/javascript .js
AddType text/css               .css
AddType image/svg+xml          .svg
AddType text/html              .html

# Serve the non-obvious entry file as the directory default
DirectoryIndex ${entry}

# ── SPA routing ───────────────────────────────────────────
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /

  # Block requests for the old predictable index.html
  RewriteRule ^index\\.html$ - [F,L]

  # Block all dotfiles except .well-known (Let's Encrypt)
  RewriteRule "(^|/)\\." - [F,L]

  # Pass through real files and directories
  RewriteCond %{REQUEST_FILENAME} -f [OR]
  RewriteCond %{REQUEST_FILENAME} -d
  RewriteRule ^ - [L]

  # All other routes → SPA entry point
  RewriteRule ^ ${entry} [L]
</IfModule>

# ── Block server-side script execution ───────────────────
# Prevents uploaded malware/web-shells from running even if
# an attacker manages to write files to the hosting account.
<FilesMatch "\\.(php|php3|php4|php5|php7|php8|phtml|phar|pl|cgi|py|rb|asp|aspx|jsp|sh|bash|exe|dll|so)$">
  Require all denied
</FilesMatch>

# ── Block access to sensitive files ──────────────────────
<FilesMatch "\\.(env|log|sql|bak|old|orig|conf|config|ini|htpasswd|htaccess|json|lock|yml|yaml|xml)$">
  Require all denied
</FilesMatch>

# Allow favicon.json/manifest if needed — add exceptions above this
<Files "favicon.svg">
  Require all granted
</Files>

# ── Security headers ──────────────────────────────────────
<IfModule mod_headers.c>
  # Prevent clickjacking
  Header always set X-Frame-Options "SAMEORIGIN"

  # Stop MIME-type sniffing
  Header always set X-Content-Type-Options "nosniff"

  # XSS filter for legacy browsers
  Header always set X-XSS-Protection "1; mode=block"

  # Referrer policy
  Header always set Referrer-Policy "strict-origin-when-cross-origin"

  # Permissions policy — disable unused browser APIs
  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=(), usb=(), bluetooth=()"

  # Cross-domain policy
  Header always set X-Permitted-Cross-Domain-Policies "none"

  # Content Security Policy
  # script-src has NO unsafe-inline — injected <script> tags will be blocked
  # even if an attacker manages to modify the HTML file on disk.
  # SRI handles the asset bundles.
  Header always set Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://images.unsplash.com blob:; connect-src 'self'; worker-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"

  # Remove server fingerprinting
  Header unset X-Powered-By
  Header unset Server
</IfModule>

# ── Block common attack patterns in query strings ─────────
<IfModule mod_rewrite.c>
  RewriteCond %{QUERY_STRING} (base64_encode|eval\\(|GLOBALS|_REQUEST) [NC,OR]
  RewriteCond %{QUERY_STRING} (<script|%3Cscript|javascript:) [NC,OR]
  RewriteCond %{QUERY_STRING} (\\.\\./|%2e%2e%2f|%252e%252e) [NC,OR]
  RewriteCond %{QUERY_STRING} (union.*select|insert.*into|drop.*table|load_file) [NC,OR]
  RewriteCond %{QUERY_STRING} (benchmark\\(|sleep\\(|%60|0x[0-9a-f]{2}) [NC]
  RewriteRule .* - [F,L]

  # Block known exploit entry points
  RewriteRule ^(wp-login|wp-admin|xmlrpc|wp-config|\\.git|\\.svn|shell|c99|r57|webshell|upload|cmd) - [F,L]
</IfModule>

# ── Block suspicious User-Agents (scanners/bots) ─────────
<IfModule mod_rewrite.c>
  RewriteCond %{HTTP_USER_AGENT} (nikto|sqlmap|nmap|masscan|dirbuster|gobuster|wfuzz|hydra|burp|zaproxy) [NC]
  RewriteRule .* - [F,L]
</IfModule>

# ── Caching ───────────────────────────────────────────────
<IfModule mod_expires.c>
  ExpiresActive On

  # Hashed bundles — immutable for 1 year
  <FilesMatch "\\.[0-9a-zA-Z]{8,}\\.(js|css)$">
    ExpiresDefault "access plus 1 year"
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>

  # Images/SVG — 30 days
  <FilesMatch "\\.(svg|png|jpg|jpeg|gif|webp|ico)$">
    ExpiresDefault "access plus 30 days"
    Header set Cache-Control "public, max-age=2592000"
  </FilesMatch>

  # HTML entry — never cache, always revalidate
  <FilesMatch "\\.html$">
    ExpiresDefault "access plus 0 seconds"
    Header set Cache-Control "no-cache, no-store, must-revalidate"
    Header set Pragma "no-cache"
  </FilesMatch>
</IfModule>

# ── Compression ───────────────────────────────────────────
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript image/svg+xml
</IfModule>
`
}

export default defineConfig({
  plugins: [react(), tailwindcss(), securePlugin()],
  build: {
    sourcemap: false,
    minify: 'oxc',
    modulePreload: false, // disabled — we use classic IIFE, not ES modules
    rollupOptions: {
      output: {
        // IIFE = classic <script> tag, NO type="module"
        // Classic scripts have NO strict MIME type enforcement.
        // Browsers execute them even if the server returns wrong Content-Type.
        format: 'iife',
        name: 'App',
        // Readable prefix + hash — pure-hash names can trigger server-side
        // security scanners (Imunify360 etc.) that flag them as obfuscated malware
        entryFileNames: 'assets/app-[hash].js',
        chunkFileNames: 'assets/app-[hash].js',
        assetFileNames: (info) => {
          if (/\.(css)$/.test(info.names?.[0] ?? '')) return 'assets/style-[hash].[ext]'
          return 'assets/[hash].[ext]'
        },
      },
    },
  },
})
